/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  docsSidebar: [
    'overview',
    'intro',
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: ['overview', 'getting-started/starter', 'getting-started/portals-intro', 'getting-started/architecture'],
    },
    {
      type: 'category',
      label: 'Build',
      collapsed: false,
      items: [
        'build/authentication',
        'build/login-view',
        'build/user-routing',
        'build/home-view',
        'build/profile-view',
        'build/hub-view',
        'build/mini-app',
      ],
    },
    {
      type: 'category',
      label: 'Connect',
      collapsed: false,
      items: ['connect/send-context'],
    },
    {
      type: 'category',
      label: 'Examples',
      collapsed: true,
      items: [
        {
          type: 'link',
          label: 'Supernova App',
          href: 'https://github.com/ionic-team/portals-super-app-demo',
        },
        {
          type: 'link',
          label: 'E-commerce App',
          href: 'https://ionic.io/docs/portals/for-ios/examples/ecommerce-app',
        },
        {
          type: 'link',
          label: 'Live Updates E-commerce App',
          href: 'https://ionic.io/docs/portals/for-ios/examples/ecommerce-app-live-updates',
        },
      ],
    },
  ],
};

module.exports = sidebars;
