/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],

  // But you can create a sidebar manually
  docsSidebar: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'overview',
        'getting-started/intro',
        'getting-started/portals-intro',
        'getting-started/starter-repo',
        'getting-started/architecture',
      ],
    },
    {
      type: 'category',
      label: 'Build',
      items: ['build/authentication', 'build/login-view', 'build/user-routing'],
    },
  ],
};

module.exports = sidebars;
